---

- name: Download .asc key and register as variable
  ansible.builtin.uri:
    url: "{{ nodejs_key_url }}"
    return_content: yes
  register: response
  until: '"PGP PUBLIC KEY" in response.content'
  retries: 10
  delay: 1

- name: Convert it into a binary .gpg because /usr/share/keyrings cannot take .asc keys
  ansible.builtin.command:
    cmd: "gpg --dearmor"
    stdin: "{{ response.content }}"
  register: output

- name: Copy key
  become: true
  ansible.builtin.copy:
    content: "{{ output.stdout }}"
    dest: "{{ nodejs_key_path }}{{ nodejs_key_name }}"

- name: Add repositories for Node.js and install it
  ansible.builtin.import_role:  
    name: ansible-role-installer
  vars:
    installer_repositories:
      - "deb [signed-by={{ nodejs_key_path }}{{ nodejs_key_name }}] https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
      - "deb-src [signed-by={{ nodejs_key_path }}{{ nodejs_key_name }}] https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    installer_packages:
      - nodejs
