---
- name: Add apt key
  ansible.builtin.import_role:
    name: ansible-role-aptkey
  vars:
    aptkey_url: "{{ nodejs_key_url }}"
    aptkey_name: "{{ nodejs_key_name }}"
    aptkey_path: "{{ nodejs_key_path }}"

- name: Ensure that repositories are installed
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ nodejs_repositories }}"

- name: Ensure that packages are installed
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ nodejs_packages }}"
