---
- name: Install nodejs
  when: nodejs_uninstall == false
  block:
    - name: Install
      ansible.builtin.include_tasks: install.yml

- name: Uninstall nodejs
  when: nodejs_uninstall == true
  block:
    - name: Uninstall
      ansible.builtin.include_tasks: uninstall.yml
