---
- name: Install nodejs
  ansible.builtin.include_tasks: install.yml
  when: nodejs_uninstall == false

- name: Uninstall nodejs
  ansible.builtin.include_tasks: uninstall.yml
  when: nodejs_uninstall == true
