---
- name: Ensure that packages are uninstalled
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    autoremove: "{{ nodejs_autoremove }}"
    purge: "{{ nodejs_purge }}"
    state: absent
  loop: "{{ nodejs_packages }}"

- name: Ensure that repositories are uninstalled
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    update_cache: true
    state: absent
  loop: "{{ nodejs_repositories }}"

- name: Remove apt key
  ansible.builtin.import_role:
    name: ansible-role-aptkey
  vars:
    aptkey_name: "{{ nodejs_key_name }}"
    aptkey_path: "{{ nodejs_key_path }}"
    aptkey_uninstall: true
