---
- name: Remove repositories for Node.js and uninstall it
  ansible.builtin.import_role:  
    name: ansible-role-installer
  vars:
    installer_repositories:
      - "deb [signed-by={{ nodejs_key_path }}{{ nodejs_key_name }}] https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
      - "deb-src [signed-by={{ nodejs_key_path }}{{ nodejs_key_name }}] https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    installer_packages:
      - nodejs
    installer_uninstall: true

- name: Update repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Remove key
  become: true
  ansible.builtin.file:
    path: "{{ nodejs_key_path }}{{ nodejs_key_name }}"
    state: absent
