---
- name: Uninstall nodejs
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: absent

- name: Remove NodeSource repositories for Node.js
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ nodejs_key_path }}{{ nodejs_key_name }}] https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    filename: "{{ nodejs_repository_name }}"
    update_cache: false 
    state: absent

- name: Remove NodeSource repositories for Node.js
  become: true
  ansible.builtin.apt_repository:
    repo: "deb-src [signed-by={{ nodejs_key_path }}{{ nodejs_key_name }}] https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    filename: "{{ nodejs_repository_name }}"
    update_cache: false 
    state: absent

- name: Update repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Remove key
  become: true
  ansible.builtin.file:
    path: "{{ nodejs_key_path }}{{ nodejs_key_name }}"
    state: absent
